spring:
  cache:
    type: redis
  application:
    name: cache
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
